### ISSUE TITLE
Diagram is incorrect

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/l1-l2-deposit-withdrawal#4]

**Comment by K-Ho** [comment]
Diagram suggests that completing a withdrawal or deposit will "mint" on the other side. This is only true for deposits, not withdrawals. For withdrawals, user's will burn L2 tokens and then send a cross domain message to transfer them tokens on L1. For deposits, users will transfer tokens into an L1 Gateway and send a cross domain message to mint L2 tokens

**Comment by platocrat** [comment]
Fixed!
